### ISSUE TITLE
【BUG】接收到‘状态’命令时出错，麻烦您修复

### ISSUE THREAD

**Issue by 2926295173** [KonnyakuCamp/SuperCourseTimetableBot#11]
1.控制台输出
```
2021-06-10 15:25:55 V/Bot.2897199320: 晴芳独韵(2926295173) -> 状态
2021-06-10 15:25:55 E/main: Exception in coroutine <unnamed>
java.lang.NoSuchMethodError: 'double com.sun.management.OperatingSystemMXBean.getCpuLoad()'
        at stageguard.sctimetable.service.BotEventRouteService$main$3$10$1.invokeSuspend(BotEventRouteService.kt:293)
        at stageguard.sctimetable.service.BotEventRouteService$main$3$10$1.invoke(BotEventRouteService.kt)
        at stageguard.sctimetable.service.BotEventRouteService$main$3$10$1.invoke(BotEventRouteService.kt)
        at stageguard.sctimetable.database.Database$suspendQuery$3.invokeSuspend(Database.kt:47)
        at stageguard.sctimetable.database.Database$suspendQuery$3.invoke(Database.kt)
        at stageguard.sctimetable.database.Database$suspendQuery$3.invoke(Database.kt)
        at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
2.我的环境
```
Running MiraiConsole v2.6.4, built on 2021-05-05 23:44:19.
Frontend Terminal: version 2.6.4, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: SuperCourseTimetable v0.4.2, Chat Command v0.5.0, MiraiWiki v2.0.1

Object Pending Finalization Count: 0
                 committed |  init  |  used  |   max
    Heap Memory:  49.08MB  | 14.0MB | 34.8MB | 199.18MB
Non-Heap Memory:  90.92MB  | 7.31MB | 87.1MB |    -1
```

**Comment by StageGuard** [comment]
应该是jdk的问题，我的测试jdk为openjdk142021年6月10日 下午3:47，AOIAN ***@***.***>写道：

1.控制台输出

2021-06-10 15:25:55 V/Bot.2897199320: 晴芳独韵(2926295173) -> 状态

2021-06-10 15:25:55 E/main: Exception in coroutine <unnamed>

java.lang.NoSuchMethodError: 'double com.sun.management.OperatingSystemMXBean.getCpuLoad()'

        at stageguard.sctimetable.service.BotEventRouteService$main$3$10$1.invokeSuspend(BotEventRouteService.kt:293)

        at stageguard.sctimetable.service.BotEventRouteService$main$3$10$1.invoke(BotEventRouteService.kt)

        at stageguard.sctimetable.service.BotEventRouteService$main$3$10$1.invoke(BotEventRouteService.kt)

        at stageguard.sctimetable.database.Database$suspendQuery$3.invokeSuspend(Database.kt:47)

        at stageguard.sctimetable.database.Database$suspendQuery$3.invoke(Database.kt)

        at stageguard.sctimetable.database.Database$suspendQuery$3.invoke(Database.kt)

        at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:126)

        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)

        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)

        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)

        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)

        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)



2.我的环境

Running MiraiConsole v2.6.4, built on 2021-05-05 23:44:19.

Frontend Terminal: version 2.6.4, provided by Mamoe Technologies



Permission Service: Built In Permission Service



Plugins: SuperCourseTimetable v0.4.2, Chat Command v0.5.0, MiraiWiki v2.01



Object Pending Finalization Count: 0

                 committed |  init  |  used  |   max

    Heap Memory:  49.08MB  | 14.0MB | 34.8MB | 199.18MB

Non-Heap Memory:  90.92MB  | 7.31MB | 87.1MB |    -1

**Comment by 2926295173** [comment]
可能是，我用的mcl安装的默认11的idk. 有点老了，我试试更新一下

**Comment by 2926295173** [comment]
还有个问题，就是我的机器人与我的qq是双向好友，我发送“帮助”，它会有反应，
但是我同学加了机器人，是单向好友.我同学发送“帮助”，就没有反应.请问这该如何解决，是否也是java的问题？

**Comment by StageGuard** [comment]
应该没有单向好友一说，申请机器人好友，会自动同意



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月10日(星期四) 晚上9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KonnyakuCamp/SuperCourseTimetableBot] 【BUG】接收到‘状态’命令时出错，麻烦您修复 (#11)





 
还有个问题，就是我的机器人与我的qq是双向好友，我发送“帮助”，它会有反应，
 但是我同学加了机器人，是单向好友.我同学发送“帮助”，就没有反应.请问这该如何解决，是否也是java的问题？
 
&mdash;

**Comment by StageGuard** [comment]
看样子是没加上好友，因为显示的是&nbsp;Stranger



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月10日(星期四) 晚上9:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KonnyakuCamp/SuperCourseTimetableBot] 【BUG】接收到‘状态’命令时出错，麻烦您修复 (#11)





 
^^^
 2021-06-10 21:49:39 V/Bot.2897199320: [Serendipity(Stranger 2542758941) -&gt; 帮助
 
ˇˇˇ
 这是我朋友加上之后，发送帮助，然后就没有反应.请问是没有加上嘛？？
 
&mdash;

**Comment by 2926295173** [comment]
您可以更改下本插件的逻辑嘛？实现陌生人就可以查询课表，不用添加好友

**Comment by StageGuard** [comment]
@2926295173 mirai 对陌生人对话的支持还不是特别完善，暂时不考虑
