### ISSUE TITLE
 -> 今日课程 2021-03-26 13:14:23 E/main: Exception in coroutine <unnamed> java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by Kided** [KonnyakuCamp/SuperCourseTimetableBot#8]
2021-03-26 13:14:23 E/main: Exception in coroutine <unnamed>
java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:662)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at stageguard.sctimetable.service.ScheduleListenerService$getSchoolTimetable$2$1.invoke(ScheduleListenerService.kt:60)
        at stageguard.sctimetable.service.ScheduleListenerService$getSchoolTimetable$2$1.invoke(ScheduleListenerService.kt:51)
        at stageguard.sctimetable.database.Database$query$2.invoke(Database.kt:42)
        at stageguard.sctimetable.database.Database$query$2.invoke(Database.kt:42)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:128)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
        at stageguard.sctimetable.database.Database.query(Database.kt:42)
        at stageguard.sctimetable.service.ScheduleListenerService.getSchoolTimetable(ScheduleListenerService.kt:51)
        at stageguard.sctimetable.service.BotEventRouteService$main$3$5$1.invokeSuspend(BotEventRouteService.kt:212)
        at stageguard.sctimetable.service.BotEventRouteService$main$3$5$1.invoke(BotEventRouteService.kt)
        at stageguard.sctimetable.service.BotEventRouteService$main$3$5$1.invoke(BotEventRouteService.kt)
        at stageguard.sctimetable.database.Database$suspendQuery$3.invokeSuspend(Database.kt:47)
        at stageguard.sctimetable.database.Database$suspendQuery$3.invoke(Database.kt)
        at stageguard.sctimetable.database.Database$suspendQuery$3.invoke(Database.kt)
        at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

不知道是什么导致的，无法导入也不能显示今日课程

**Comment by StageGuard** [comment]
可能是超级课表中没有记录时间表信息。
2.0版本将会重构，等等吧

**Comment by Kided** [comment]
> 可能是超级课表中没有记录时间表信息。
> 2.0版本将会重构，等等吧

了解了，感谢

**Comment by StageGuard** [comment]
可能已经修复了
