### ISSUE TITLE
在修改周数之后出现越界问题

### ISSUE THREAD

**Issue by Nothingness-Void** [KonnyakuCamp/SuperCourseTimetableBot#9]
2021-05-06 20:50:12 E/SuperCourseTimetable: Exception in coroutine Plugin SuperCourseTimetable of SuperCourseTimetable
java.lang.IndexOutOfBoundsException: Index 8 out of bounds for length 7
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at stageguard.sctimetable.service.ScheduleListenerService.startUserNotificationJob(ScheduleListenerService.kt:150)
        at stageguard.sctimetable.service.ScheduleListenerService$onChangeSchoolWeekPeriod$1$1.invokeSuspend(ScheduleListenerService.kt:207)
        at stageguard.sctimetable.service.ScheduleListenerService$onChangeSchoolWeekPeriod$1$1.invoke(ScheduleListenerService.kt)
        at stageguard.sctimetable.service.ScheduleListenerService$onChangeSchoolWeekPeriod$1$1.invoke(ScheduleListenerService.kt)
        at stageguard.sctimetable.database.Database$suspendQuery$3.invokeSuspend(Database.kt:47)
        at stageguard.sctimetable.database.Database$suspendQuery$3.invoke(Database.kt)
        at stageguard.sctimetable.database.Database$suspendQuery$3.invoke(Database.kt)
        at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by StageGuard** [comment]
应该是缓存没修改。。重启一下console试试
现在的设计很糟糕，我准备在 2.0 重构所有代码

**Comment by Nothingness-Void** [comment]
> 应该是缓存没修改。。重启一下console试试
> 现在的设计很糟糕，我准备在 2.0 重构所有代码

emmm重启了并不管用

**Comment by StageGuard** [comment]
> > 应该是缓存没修改。。重启一下console试试
> > 现在的设计很糟糕，我准备在 2.0 重构所有代码
> 
> emmm重启了并不管用

看看数据库对应学校的时间表中 `timelist` 项，是否是正确的时间表信息

**Comment by Nothingness-Void** [comment]
> > > 应该是缓存没修改。。重启一下console试试
> > > 现在的设计很糟糕，我准备在 2.0 重构所有代码
> > 
> > 
> > emmm重启了并不管用
> 
> 看看数据库对应学校的时间表中 `timelist` 项，是否是正确的时间表信息

没显示全 timelist项的数据长度加倍了 我去试试。
